dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),  # 购物车模块
    url(r'^', include('df_goods.urls', namespace='goods')),  # 商品模块
    url(r'^order/', include('df_order.urls', namespace='order')),  # 订单模块
    url(r'^user/', include('df_user.urls', namespace='user')),  # 用户模块
    url(r'^search/', include('haystack.urls')),  # 全文检索框架
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
]

df_cart/urls.py
from django.conf.urls import url
from df_cart import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'),  # 往购物车添加商品
    url(r'^$', views.cart_show, name='show'),  # 购物车页面
    url(r'^count/$', views.cart_count, name='count'),  # 购物车商品数目
    url(r'update/$', views.update, name='update'),  # 更新redis数据库
    url(r'delete/$', views.delete, name='delete'),  # 删除商品

]

df_goods/urls.py
from django.conf.urls import url
from df_goods import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),  # 网站主页面
    url(r'^detail(?P<goods_id>\d+)/$', views.goods_detail, name='detail'),  # 商品详情
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.goods_list, name='list'),  # 商品列表
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),  # 购物车模块
    url(r'^', include('df_goods.urls', namespace='goods')),  # 商品模块
    url(r'^order/', include('df_order.urls', namespace='order')),  # 订单模块
    url(r'^user/', include('df_user.urls', namespace='user')),  # 用户模块
    url(r'^search/', include('haystack.urls')),  # 全文检索框架
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
]

df_goods/models.py
from django.db import models
from db.base_model import BaseModel
from df_goods.enums import *
from tinymce.models import HTMLField
# Create your models here.


class GoodsManage(models.Manager):
    '''商品模型管理器类'''
    def get_goods_by_type(self, type_id, limit=None, sort='default'):  # default为默认参数
        # 通过商品种类查询商品
        if sort == 'new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-sales',)
        elif sort == 'price':
            order_by = ('price',)
        else:
            order_by = ('-pk',)
        goods_li = self.filter(type_id=type_id).order_by(*order_by)
        # 查询结果集的限制
        if limit:
            goods_li = goods_li[:limit]  # 将列表切片
        return goods_li

    def get_goods_by_id(self, goods_id):
        '''根据商品的id获取商品的信息'''
        try:
            goods = self.get(id=goods_id)
        except self.model.DoesNotExist:
            # 不存在商品信息
            goods = None
        return goods


class Goods(BaseModel):
    '''商品模型类'''
    goods_type_choices = ((k, v) for k, v in GOODS_TYPES.items())
    status_choices = ((k, v) for k, v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=FRUIT, choices=goods_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=256, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品单价')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')

    objects = GoodsManage()

    class Meta:
        db_table = 's_goods'


class ImageManage(models.Manager):
    '''商品图片模型管理器类'''
    pass


class GoodsImage(BaseModel):
    '''图片模型类'''
    goods = models.ForeignKey('goods', verbose_name='所属商品')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')

    objects = ImageManage()

    class Meta:
        db_table = 's_goods_image'

df_goods/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from df_goods.models import Goods, GoodsImage
from df_goods.enums import *
from django_redis import get_redis_connection
from django.core.paginator import Paginator

# Create your views here.


# /index/
def index(request):
    '''显示主页面'''
    # 查询每个商品种类3条新品信息和4条销量最高的商品
    fruit_new = Goods.objects.get_goods_by_type(FRUIT, 3, sort='new')
    fruit_hot = Goods.objects.get_goods_by_type(FRUIT, 4, sort='hot')
    seafood_new = Goods.objects.get_goods_by_type(SEAFOOD, 3, sort='new')
    seafood_hot = Goods.objects.get_goods_by_type(SEAFOOD, 4, sort='hot')
    meat_new = Goods.objects.get_goods_by_type(MEAT, 3, sort='new')
    meat_hot = Goods.objects.get_goods_by_type(MEAT, 4, sort='hot')
    eggs_new = Goods.objects.get_goods_by_type(EGGS, 3, sort='new')
    eggs_hot = Goods.objects.get_goods_by_type(EGGS, 4, sort='hot')
    vegetables_new = Goods.objects.get_goods_by_type(VEGETABLES, 3, sort='new')
    vegetables_hot = Goods.objects.get_goods_by_type(VEGETABLES, 4, sort='hot')
    frozen_new = Goods.objects.get_goods_by_type(FROZEN, 3, sort='new')
    frozen_hot = Goods.objects.get_goods_by_type(FROZEN, 4, sort='hot')
    # 定义模板上下文
    context = {'fruit_new': fruit_new, 'fruit_hot': fruit_hot,
               'seafood_new': seafood_new, 'seafood_hot': seafood_hot,
               'meat_new': meat_new, 'meat_hot': meat_hot,
               'eggs_new': eggs_new, 'eggs_hot': eggs_hot,
               'vegetables_new': vegetables_new, 'vegetables_hot': vegetables_hot,
               'frozen_new': frozen_new, 'frozen_hot': frozen_hot}
    return render(request, 'df_goods/index.html', context)


# /list/
def list(request, goods_id):
    '''显示商品列表页面'''
    # 获取商品的详细信息(位置参数)
    goods = Goods.objects.get_goods_by_type(goods_id=goods_id)
    if goods is None:
        # 如果商品不存在，返回首页
        return redirect(reversed('goods:index'))
    # 获取商品的详情图片
    images = GoodsImage.objects.filter(goods_id=goods_id)
    if images.exists():
        # 有图片
        image = images[0]
    else:
        # 没有图片
        image = ''
    return render(request, 'df_goods/list.html')


# /detail/
def goods_detail(request, goods_id):
    '''显示商品详细信息'''
    # 获取商品的详细信息
    goods = Goods.objects.get_goods_by_id(goods_id=goods_id)
    if goods is None:
        # 商品不存在，跳转到首页
        return redirect(reverse('goods:index'))
    # 获取商品的详情图片
    images = GoodsImage.objects.filter(goods_id=goods_id)
    if images.exists():
        # 有图片
        images = images[0]
    else:
        # 没有图片
        images = ''
    # 新品推荐
    goods_li = Goods.objects.get_goods_by_type(type_id=goods.type_id, limit=2, sort='new')
    # 用户登录后，才记录浏览记录
    if request.session.has_key('islogin'):
        # 用户已经登录，记录浏览记录
        con = get_redis_connection('default')
        key = 'history_%d' % request.session.get('passport_id')
        # 先从redis列表中移除goods_id
        con.lrem(key, 0, goods_id)
        # 将商品浏览记录添加到列表中
        con.lpush(key, goods_id)
        # 保存用户最近浏览的5个商品
        con.ltrim(key, 0, 4)
    # 定义上下文
    context = {'goods': goods, 'goods_li': goods_li, 'images': images}
    return render(request, 'df_goods/detail.html', context)


# 商品种类 页码 排序方式
# /list/(种类id)/(页码)/?sort=排序方式
def goods_list(request, type_id, page):
    '''显示商品列表'''
    # 获取排序方式
    sort = request.GET.get('sort', 'default')
    # 判断type_id是否合法
    if int(type_id) not in GOODS_TYPES.keys():
        return redirect(reverse('goods:index'))
    # 根据商品种类id和排序方式查询数据
    goods_li = Goods.objects.get_goods_by_type(type_id=type_id, sort=sort)
    # 分页
    paginator = Paginator(goods_li, 1)
    # 获取分页之后的总页数
    num_pages = paginator.num_pages
    # 获取第page页的数据
    if page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)
    # 返回值是一个page类的实例对象
    goods_li = paginator.page(page)
    # 页码控制
    if num_pages < 5:
        pages = range(1, num_pages+1)
    elif page <= 3:
        pages = range(1, 6)
    elif num_pages - page <= 2:
        pages = range(num_pages-4, num_pages+1)
    else:
        pages = range(page-2, page+3)
    # 新品推荐
    goods_new = Goods.objects.get_goods_by_type(type_id=type_id, limit=2, sort='new')
    # 定义上下文
    type_title = GOODS_TYPES[int(type_id)]
    context = {'goods_li': goods_li, 'goods_new': goods_new,
               'type_id': type_id, 'sort': sort,
               'type_title': type_title, 'pages': pages}
    # 使用模板
    return render(request, 'df_goods/list.html', context)

templates/df_goods/detail.html
{% extends 'detail_list_base.html' %}
{% load staticfiles %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/detail.js' %}"></script>
{% endblock topfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% block main_content %}
    <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>
    <div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{% static goods.image %}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.price }}</em></span>
				<span class="show_unit">单  位：{{ goods.unite }}g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart" goods_id="{{ goods.id }}">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for goods in goods_li %}
					<li>
						<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
						<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
						<div class="prize">￥{{ goods.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.detail|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock main_content %}
{% block bottomhtml %}
	<div class="add_jump"></div>
{% endblock bottomhtml %}

templates/df_goods/index.html
{% extends 'search/../base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
    	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for goods in fruit_new %}
				<a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
			<ul class="goods_list fl">
                {% for goods in fruit_hot %}
				<li>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<div class="prize">¥ {{ goods.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for goods in seafood_new %}
				<a href="url 'goods:detail' goods_id=goods.id">{{ goods.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner02.jpg'%}"></div>
			<ul class="goods_list fl">
                {% for goods in seafood_hot %}
				<li>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<div class="prize">¥ {{ goods.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for goods in meat_new %}
				<a href="url 'goods:detail' goods_id=goods.id">{{ goods.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
			<ul class="goods_list fl">
                {% for goods in meat_hot %}
				<li>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<div class="prize">¥ {{ goods.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for goods in eggs_new %}
				<a href="url 'goods:detail' goods_id=goods.id">{{ goods.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner04.jpg'%}"></div>
			<ul class="goods_list fl">
				{% for goods in eggs_hot %}
				<li>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<div class="prize">¥ {{ goods.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for goods in vegetables_new %}
				<a href="url 'goods:detail' goods_id=goods.id">{{ goods.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner05.jpg'%}"></div>
			<ul class="goods_list fl">
				{% for goods in vegetables_hot %}
				<li>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<div class="prize">¥ {{ goods.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for goods in frozen_new %}
				<a href="url 'goods:detail' goods_id=goods.id">{{ goods.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static 'images/banner06.jpg'%}"></div>
			<ul class="goods_list fl">
				{% for goods in frozen_hot %}
				<li>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<div class="prize">¥ {{ goods.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
{% endblock body%}

templates/df_goods/list.html
{% extends 'detail_list_base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type_title }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for goods in goods_new %}
					<li>
						<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
						<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
						<div class="prize">￥{{ goods.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="/list/{{ type_id }}/1/" {% if sort == 'default' %} class="active" {% endif %}>默认</a>
				<a href="/list/{{ type_id }}/1/?sort=price" {% if sort == 'price' %} class="active" {% endif %}>价格</a>
				<a href="/list/{{ type_id }}/1/?sort=hot" {% if sort == 'hot' %} class="active" {% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for goods in goods_li %}
                <li>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.price }}</span>
						<span class="unit">{{ goods.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if goods_li.has_previous %}
                    <a href="/list/{{ type_id }}/{{ goods_li.previous_page_number }}/?sort={{ sort }}"><上一页</a>
                {% else %}
                    <a>上一页></a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == goods_li.number %}
				        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}" class="active">{{ pindex }}</a>
				    {% else %}
                        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if goods_li.has_next %}
                    <a href="/list/{{ type_id }}/{{ goods_li.next_page_number }}/?sort={{ sort }}">下一页></a>
                {% else %}
                    <a><下一页</a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}