dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),  # 购物车模块
    url(r'^', include('df_goods.urls', namespace='goods')),  # 商品模块
    url(r'^order/', include('df_order.urls', namespace='order')),  # 订单模块
    url(r'^user/', include('df_user.urls', namespace='user')),  # 用户模块
    url(r'^search/', include('haystack.urls')),  # 全文检索框架
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
]

df_cart/urls.py
from django.conf.urls import url
from df_cart import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'),  # 往购物车添加商品
    url(r'^$', views.cart_show, name='show'),  # 购物车页面
    url(r'^count/$', views.cart_count, name='count'),  # 购物车商品数目
    url(r'update/$', views.update, name='update'),  # 更新redis数据库
    url(r'delete/$', views.delete, name='delete'),  # 删除商品

]

df_user/urls.py
from django.conf.urls import url
from df_user import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),  # 显示注册页面
    url(r'^register_handles/$', views.register_handles, name='register_handles'),  # 用户注册
    url(r'^login/$', views.login, name='login'),  # 显示注册页面
    url(r'^check_user_exist/$', views.check_user_exist, name='check_user_exist'),  # 判断用户是否存在
    url(r'^active/(?P<token>.*)/$', views.register_active, name='active'),  # 邮箱激活账户
    url(r'^login_check/$', views.login_check, name='login_check'),  # 用户登录
    url(r'^logout/$', views.logout, name='logout'),  # 退出用户登录
    url(r'^$', views.user, name='user'),  # 用户中心-信息页
    url(r'^order/$', views.order, name='order'),  # 用户中心-订单页
    url(r'^address/$', views.address, name='address'),  # 用户中心-地址页
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),  # 购物车模块
    url(r'^', include('df_goods.urls', namespace='goods')),  # 商品模块
    url(r'^order/', include('df_order.urls', namespace='order')),  # 订单模块
    url(r'^user/', include('df_user.urls', namespace='user')),  # 用户模块
    url(r'^search/', include('haystack.urls')),  # 全文检索框架
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
]

templates/base.html
{# 首页 登录 注册 的父模板 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页顶部标题块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.session.islogin %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="/index/" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search/">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body %}{% endblock body %}
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{# 网页底部引入heml块元素 #}
{% block bottomhtml%}{% endblock bottomhtml %}
{# 网页底部引入文件块 #}
{% block bottomfiles%}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $.get('/cart/count/', function (data) {
            // {'res':商品的总数}
            $('#show_count').html(data.res)
        })
    </script>
{% endblock bottomfiles %}
</body>
</html>

templates/detail_list_base.html
{# 详情 列表 的父模板 #}
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list/1/1" class="fruit">新鲜水果</a></li>
					<li><a href="/list/2/1" class="seafood">海鲜水产</a></li>
					<li><a href="/list/3/1" class="meet">猪牛羊肉</a></li>
					<li><a href="/list/4/1" class="egg">禽类蛋品</a></li>
					<li><a href="/list/5/1" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="/list/6/1" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/not_cart_base.html
{# 购物车 提交订单 的父模板 #}
{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
      <div class="search_bar clearfix">
		<a href="/index/" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

templates/user_center_base.html
{# 用户中心页面的父模板 #}
{% extends 'not_cart_base.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
            <div class="left_menu_con clearfix">
                <h3>用户中心</h3>
                <ul>
                    <li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
                    <li><a href="{% url 'user:order' %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
                    <li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
                </ul>
            </div>
            {# 用户中心右侧内容块 #}
            {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}